#FROM python:3.6.12
FROM python:alpine
LABEL maintainer="kai.cao"

ENV PIP_INDEX_URL=https://pypi.doubanio.com/simple
ENV PYTHONUNBUFFERED=1

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories
RUN apk update && \
    apk add --no-cache ca-certificates && \
    apk add --no-cache --virtual .build-deps python3-dev libffi-dev gcc musl-dev make

RUN pip install --upgrade pip

RUN mkdir /app
WORKDIR /app
COPY requirements.txt /app/
RUN pip install -r requirements.txt
RUN pip install -U --force-reinstall --no-binary :all: gevent
COPY . /app/

# 安装完成后清理缓存
RUN apk del .build-deps python3-dev libffi-dev gcc musl-dev make && \
    rm -rf /var/cache/apk/*

RUN rm -rf /var/cache/

EXPOSE 5001
#ENTRYPOINT ["python", "server.py"]
ENTRYPOINT ["gunicorn", "server:app"]
CMD ["-c", "gunicorn_conf.py", "-k", "gevent"]